---
#
# THIS IS A DUMMY WORKFLOW
# It's used to create a Docker layer used as cache for the dev.yml workflow, using act.
#
name: cache

on:
  push:
    branches:
      - dummy_cache_branch_that_does_not_exist

jobs:

  layer:
    name: layer
    runs-on: ubuntu-latest
    env:
      using_act: ${{ github.actor == 'nektos/act'}}

    steps:

      - name: Checkout.
        uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip' # caching pip dependencies

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies

      - name: Make sure path are there also for act shells.
        if: env.using_act == 'true'
        run: |
          echo "export PATH=\"/opt/hostedtoolcache/Python/${{ env.python_version }}/x64:/opt/hostedtoolcache/Python/${{ env.python_version }}/x64/bin:$PATH\"" >> /root/.bashrc

      - name: Upgrade pip.
        run: python -m pip install --upgrade pip

      - name: Install poetry and invoke.
        run: pip install poetry invoke

      - name: Configure poetry
        run: poetry config --local virtualenvs.in-project false && poetry config --local virtualenvs.path "~/venvs"

      - name: Install the first python venv
        run: inv env.init --all
